/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV1CalendarsRouteImport } from './routes/api/v1/calendars'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1LinkInitRouteImport } from './routes/api/v1/link/init'
import { Route as ApiV1CalendarsCalendarIdRouteImport } from './routes/api/v1/calendars/$calendarId'
import { Route as ApiV1CalendarsCalendarIdEventsRouteImport } from './routes/api/v1/calendars/$calendarId/events'
import { Route as ApiV1CalendarsCalendarIdEventsEventIdRouteImport } from './routes/api/v1/calendars/$calendarId/events/$eventId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CalendarsRoute = ApiV1CalendarsRouteImport.update({
  id: '/api/v1/calendars',
  path: '/api/v1/calendars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LinkInitRoute = ApiV1LinkInitRouteImport.update({
  id: '/api/v1/link/init',
  path: '/api/v1/link/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CalendarsCalendarIdRoute =
  ApiV1CalendarsCalendarIdRouteImport.update({
    id: '/$calendarId',
    path: '/$calendarId',
    getParentRoute: () => ApiV1CalendarsRoute,
  } as any)
const ApiV1CalendarsCalendarIdEventsRoute =
  ApiV1CalendarsCalendarIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => ApiV1CalendarsCalendarIdRoute,
  } as any)
const ApiV1CalendarsCalendarIdEventsEventIdRoute =
  ApiV1CalendarsCalendarIdEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => ApiV1CalendarsCalendarIdEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/settings': typeof SettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/calendars': typeof ApiV1CalendarsRouteWithChildren
  '/api/v1/calendars/$calendarId': typeof ApiV1CalendarsCalendarIdRouteWithChildren
  '/api/v1/link/init': typeof ApiV1LinkInitRoute
  '/api/v1/calendars/$calendarId/events': typeof ApiV1CalendarsCalendarIdEventsRouteWithChildren
  '/api/v1/calendars/$calendarId/events/$eventId': typeof ApiV1CalendarsCalendarIdEventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/settings': typeof SettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/calendars': typeof ApiV1CalendarsRouteWithChildren
  '/api/v1/calendars/$calendarId': typeof ApiV1CalendarsCalendarIdRouteWithChildren
  '/api/v1/link/init': typeof ApiV1LinkInitRoute
  '/api/v1/calendars/$calendarId/events': typeof ApiV1CalendarsCalendarIdEventsRouteWithChildren
  '/api/v1/calendars/$calendarId/events/$eventId': typeof ApiV1CalendarsCalendarIdEventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/settings': typeof SettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/calendars': typeof ApiV1CalendarsRouteWithChildren
  '/api/v1/calendars/$calendarId': typeof ApiV1CalendarsCalendarIdRouteWithChildren
  '/api/v1/link/init': typeof ApiV1LinkInitRoute
  '/api/v1/calendars/$calendarId/events': typeof ApiV1CalendarsCalendarIdEventsRouteWithChildren
  '/api/v1/calendars/$calendarId/events/$eventId': typeof ApiV1CalendarsCalendarIdEventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/settings'
    | '/api/auth/$'
    | '/api/v1/calendars'
    | '/api/v1/calendars/$calendarId'
    | '/api/v1/link/init'
    | '/api/v1/calendars/$calendarId/events'
    | '/api/v1/calendars/$calendarId/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/settings'
    | '/api/auth/$'
    | '/api/v1/calendars'
    | '/api/v1/calendars/$calendarId'
    | '/api/v1/link/init'
    | '/api/v1/calendars/$calendarId/events'
    | '/api/v1/calendars/$calendarId/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/settings'
    | '/api/auth/$'
    | '/api/v1/calendars'
    | '/api/v1/calendars/$calendarId'
    | '/api/v1/link/init'
    | '/api/v1/calendars/$calendarId/events'
    | '/api/v1/calendars/$calendarId/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  SettingsRoute: typeof SettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1CalendarsRoute: typeof ApiV1CalendarsRouteWithChildren
  ApiV1LinkInitRoute: typeof ApiV1LinkInitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/calendars': {
      id: '/api/v1/calendars'
      path: '/api/v1/calendars'
      fullPath: '/api/v1/calendars'
      preLoaderRoute: typeof ApiV1CalendarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/link/init': {
      id: '/api/v1/link/init'
      path: '/api/v1/link/init'
      fullPath: '/api/v1/link/init'
      preLoaderRoute: typeof ApiV1LinkInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/calendars/$calendarId': {
      id: '/api/v1/calendars/$calendarId'
      path: '/$calendarId'
      fullPath: '/api/v1/calendars/$calendarId'
      preLoaderRoute: typeof ApiV1CalendarsCalendarIdRouteImport
      parentRoute: typeof ApiV1CalendarsRoute
    }
    '/api/v1/calendars/$calendarId/events': {
      id: '/api/v1/calendars/$calendarId/events'
      path: '/events'
      fullPath: '/api/v1/calendars/$calendarId/events'
      preLoaderRoute: typeof ApiV1CalendarsCalendarIdEventsRouteImport
      parentRoute: typeof ApiV1CalendarsCalendarIdRoute
    }
    '/api/v1/calendars/$calendarId/events/$eventId': {
      id: '/api/v1/calendars/$calendarId/events/$eventId'
      path: '/$eventId'
      fullPath: '/api/v1/calendars/$calendarId/events/$eventId'
      preLoaderRoute: typeof ApiV1CalendarsCalendarIdEventsEventIdRouteImport
      parentRoute: typeof ApiV1CalendarsCalendarIdEventsRoute
    }
  }
}

interface ApiV1CalendarsCalendarIdEventsRouteChildren {
  ApiV1CalendarsCalendarIdEventsEventIdRoute: typeof ApiV1CalendarsCalendarIdEventsEventIdRoute
}

const ApiV1CalendarsCalendarIdEventsRouteChildren: ApiV1CalendarsCalendarIdEventsRouteChildren =
  {
    ApiV1CalendarsCalendarIdEventsEventIdRoute:
      ApiV1CalendarsCalendarIdEventsEventIdRoute,
  }

const ApiV1CalendarsCalendarIdEventsRouteWithChildren =
  ApiV1CalendarsCalendarIdEventsRoute._addFileChildren(
    ApiV1CalendarsCalendarIdEventsRouteChildren,
  )

interface ApiV1CalendarsCalendarIdRouteChildren {
  ApiV1CalendarsCalendarIdEventsRoute: typeof ApiV1CalendarsCalendarIdEventsRouteWithChildren
}

const ApiV1CalendarsCalendarIdRouteChildren: ApiV1CalendarsCalendarIdRouteChildren =
  {
    ApiV1CalendarsCalendarIdEventsRoute:
      ApiV1CalendarsCalendarIdEventsRouteWithChildren,
  }

const ApiV1CalendarsCalendarIdRouteWithChildren =
  ApiV1CalendarsCalendarIdRoute._addFileChildren(
    ApiV1CalendarsCalendarIdRouteChildren,
  )

interface ApiV1CalendarsRouteChildren {
  ApiV1CalendarsCalendarIdRoute: typeof ApiV1CalendarsCalendarIdRouteWithChildren
}

const ApiV1CalendarsRouteChildren: ApiV1CalendarsRouteChildren = {
  ApiV1CalendarsCalendarIdRoute: ApiV1CalendarsCalendarIdRouteWithChildren,
}

const ApiV1CalendarsRouteWithChildren = ApiV1CalendarsRoute._addFileChildren(
  ApiV1CalendarsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  SettingsRoute: SettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1CalendarsRoute: ApiV1CalendarsRouteWithChildren,
  ApiV1LinkInitRoute: ApiV1LinkInitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
